version: '3'


services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  app:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: node
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "1-20"
    volumes:
      - ..:/workspaces/gif-harvester:cached
      #- $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github
    environment:
      - NODE_ENV=development
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


